create table Usuario (id int identity(1, 1) not null, nombreUsuario varchar(50) not null unique, Rolid int not null, pass varchar(255) not null, primary key (id));
create table Rol (id int identity(1, 1) not null, descripcionRol varchar(15) not null unique, primary key (id));
create table ParametrosGenerales (codigoEmpresa int not null, nombreEmpresa varchar(255) not null, fechaActual datetime not null, zafraAct int not null, primary key (codigoEmpresa));
create table TiposSectorPropiedad (id int identity(1, 1) not null, nombreTipoSector varchar(10) not null, primary key (id));
create table MarcasCombinadas (id int identity(1, 1) not null, nombreCombinada varchar(50) not null unique, primary key (id));
create table OperadorCombinada (id int identity(1, 1) not null, nombreOperador varchar(255) not null, MarcasCombinadasid int not null, PelotonCombinadasid int not null, primary key (id));
create table Suministradores (id int identity(1, 1) not null, TiposSectorPropiedadid int not null, nombreSuministrador varchar(100) not null, primary key (id), constraint uniquesum unique (TiposSectorPropiedadid, nombreSuministrador));
create table PelotonCombinadas (id int identity(1, 1) not null, Suministradoresid int not null, parque int not null, primary key (id));
create table CentrosRecepcion (id int identity(1, 1) not null, nombreCentroRecepcion varchar(100) not null unique, primary key (id));
create table TipoEquipos (id int identity(1, 1) not null, descripcionEquipo varchar(100) not null unique, primary key (id));
create table PlanEquiposAgricZafra (id int identity(1, 1) not null, ParqueEquiposid int not null, parqueAsignado int not null, tareaDiaria decimal(19, 2) not null, CentrosRecepcionid int not null, Zafrasid int not null, primary key (id), constraint uniqueplaneq unique (ParqueEquiposid, CentrosRecepcionid, Zafrasid));
create table PlanOperadoresCombinadas (id int identity(1, 1) not null, OperadorCombinadaid int not null, tareaDiaria decimal(19, 2) not null, CentrosRecepcionid int not null, Zafrasid int not null, primary key (id), constraint uniqueplanop unique (OperadorCombinadaid, CentrosRecepcionid, Zafrasid));
create table DiarioOperadorCombinadas (OperadorCombinadaid int not null, fecha datetime not null, Campoid int not null, EstadoEquipoid int not null, cantQuemada decimal(19, 2) not null, cantQuemadaProgram decimal(19, 2) not null, cantVerde decimal(19, 2) not null, Usuarioid int not null, Zafrasid int not null, primary key (OperadorCombinadaid, fecha), constraint uniquediarioop unique (OperadorCombinadaid, fecha));
create table DiarioEquiposZafra (PlanEquiposAgricZafraid int not null, fecha datetime not null, arrobasTiradas decimal(19, 2) not null, parqueParado int not null, Usuarioid int not null, Zafrasid int not null, primary key (PlanEquiposAgricZafraid, fecha), constraint uniquediarioeq unique (PlanEquiposAgricZafraid, fecha));
create table EstadoEquipo (id int identity(1, 1) not null, nombreEstado varchar(10) not null unique, primary key (id));
create table VariedadCana (id int identity(1, 1) not null, nombreVariedad varchar(10) not null unique, primary key (id));
create table Campo (id int identity(1, 1) not null, Suministradoresid int not null, VariedadCanaid int not null, cepa varchar(50) not null, cantCanaVerde decimal(19, 2) not null, cantCanaQuemada decimal(19, 2) not null, primary key (id));
create table ParqueEquipos (id int identity(1, 1) not null, Suministradoresid int not null, TipoEquiposid int not null, cantidadEquipos int not null, primary key (id), constraint uniqueparque unique (TipoEquiposid, Suministradoresid));
create table Zafras (id int identity(1, 1) not null, descripcionZafra varchar(9) not null unique, fechaInicio datetime not null, fechaFin datetime null, primary key (id));
alter table PlanOperadoresCombinadas add constraint FKPlanOperad22800 foreign key (CentrosRecepcionid) references CentrosRecepcion (id);
alter table PlanOperadoresCombinadas add constraint FKPlanOperad741560 foreign key (Zafrasid) references Zafras (id);
alter table PlanOperadoresCombinadas add constraint FKPlanOperad482811 foreign key (OperadorCombinadaid) references OperadorCombinada (id);
alter table OperadorCombinada add constraint FKOperadorCo455168 foreign key (MarcasCombinadasid) references MarcasCombinadas (id);
alter table OperadorCombinada add constraint FKOperadorCo809279 foreign key (PelotonCombinadasid) references PelotonCombinadas (id);
alter table PelotonCombinadas add constraint FKPelotonCom54014 foreign key (Suministradoresid) references Suministradores (id);
alter table Suministradores add constraint FKSuministra562195 foreign key (TiposSectorPropiedadid) references TiposSectorPropiedad (id);
alter table Campo add constraint FKCampo53335 foreign key (VariedadCanaid) references VariedadCana (id);
alter table Campo add constraint FKCampo161005 foreign key (Suministradoresid) references Suministradores (id);
alter table DiarioOperadorCombinadas add constraint FKDiarioOper849218 foreign key (OperadorCombinadaid) references OperadorCombinada (id);
alter table PlanEquiposAgricZafra add constraint FKPlanEquipo587695 foreign key (Zafrasid) references Zafras (id);
alter table PlanEquiposAgricZafra add constraint FKPlanEquipo352056 foreign key (CentrosRecepcionid) references CentrosRecepcion (id);
alter table PlanEquiposAgricZafra add constraint FKPlanEquipo297757 foreign key (ParqueEquiposid) references ParqueEquipos (id);
alter table ParametrosGenerales add constraint FKParametros205676 foreign key (zafraAct) references Zafras (id);
alter table DiarioOperadorCombinadas add constraint FKDiarioOper822334 foreign key (Campoid) references Campo (id);
alter table DiarioOperadorCombinadas add constraint FKDiarioOper578327 foreign key (EstadoEquipoid) references EstadoEquipo (id);
alter table DiarioOperadorCombinadas add constraint FKDiarioOper626817 foreign key (Usuarioid) references Usuario (id);
alter table DiarioOperadorCombinadas add constraint FKDiarioOper897999 foreign key (Zafrasid) references Zafras (id);
alter table Usuario add constraint FKUsuario38509 foreign key (Rolid) references Rol (id);
alter table DiarioEquiposZafra add constraint FKDiarioEqui859692 foreign key (Usuarioid) references Usuario (id);
alter table DiarioEquiposZafra add constraint FKDiarioEqui334875 foreign key (Zafrasid) references Zafras (id);
alter table ParqueEquipos add constraint FKParqueEqui70865 foreign key (TipoEquiposid) references TipoEquipos (id);
alter table ParqueEquipos add constraint FKParqueEqui172425 foreign key (Suministradoresid) references Suministradores (id);
alter table DiarioEquiposZafra add constraint FKDiarioEqui435805 foreign key (PlanEquiposAgricZafraid) references PlanEquiposAgricZafra (id);
create unique index Usuario_id on Usuario (id);
create unique index Rol_id on Rol (id);
create unique index ParametrosGenerales_codigoEmpresa on ParametrosGenerales (codigoEmpresa);
create unique index TiposSectorPropiedad_id on TiposSectorPropiedad (id);
create unique index MarcasCombinadas_id on MarcasCombinadas (id);
create unique index OperadorCombinada_id on OperadorCombinada (id);
create unique index Suministradores_id on Suministradores (id);
create unique index PelotonCombinadas_id on PelotonCombinadas (id);
create unique index CentrosRecepcion_id on CentrosRecepcion (id);
create unique index TipoEquipos_id on TipoEquipos (id);
create unique index PlanEquiposAgricZafra_id on PlanEquiposAgricZafra (id);
create unique index PlanOperadoresCombinadas_id on PlanOperadoresCombinadas (id);
create index DiarioEquiposZafra_fecha on DiarioEquiposZafra (fecha);
create unique index EstadoEquipo_id on EstadoEquipo (id);
create unique index VariedadCana_id on VariedadCana (id);
create unique index Campo_id on Campo (id);
create unique index ParqueEquipos_id on ParqueEquipos (id);
create unique index Zafras_id on Zafras (id);
