//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campo
    {
        public Campo()
        {
            this.DiarioOperadorCombinadas = new HashSet<DiarioOperadorCombinadas>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        public int Suministradoresid { get; set; }

        [Display(Name = "Caña Verde")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        [Range(0, Double.MaxValue, ErrorMessage = "El valor debe ser positivo")]
        public decimal cantCanaVerde { get; set; }

        [Display(Name = "Caña Quemada")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        [Range(0,Double.MaxValue,ErrorMessage = "El valor debe ser positivo")]
        public decimal cantCanaQuemada { get; set; }

        [Display(Name = "Cepa")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        [RegularExpression(@"[fpr]\d{4,5}",ErrorMessage = "Debe seguir este patron [estacion][año] o [cant cortes][año](Ej: p2014 f2014 r12014) ")]
        public string cepa { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        public int VariedadCanaid { get; set; }
    
        public virtual Suministradores Suministradores { get; set; }
        public virtual VariedadCana VariedadCana { get; set; }
        public virtual ICollection<DiarioOperadorCombinadas> DiarioOperadorCombinadas { get; set; }
    }
}
