//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentrosRecepcion
    {
        public CentrosRecepcion()
        {
            this.PlanEquiposAgricZafra = new HashSet<PlanEquiposAgricZafra>();
            this.PlanOperadoresCombinadas = new HashSet<PlanOperadoresCombinadas>();
        }
    
        public int id { get; set; }

        [Display(Name = "Centro de Recepcion")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        [Remote("CheckCentro", "CentrosRecepcion", AdditionalFields = "id", ErrorMessage = "Ya existe esta zafra")]
        public string nombreCentroRecepcion { get; set; }
    
        public virtual ICollection<PlanEquiposAgricZafra> PlanEquiposAgricZafra { get; set; }
        public virtual ICollection<PlanOperadoresCombinadas> PlanOperadoresCombinadas { get; set; }
    }
}
