//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiarioOperadorCombinadas
    {
        [Required(ErrorMessage = "Este Campo es requerido")]
        public int PlanOperadoresCombinadasid { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        public System.DateTime fecha { get; set; }

        public int Campoid { get; set; }

        public int EstadoEquipoid { get; set; }

        [Display(Name = "Caña Quemada")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        [Range(0, Double.MaxValue, ErrorMessage = "El valor debe ser positivo")]
        public decimal cantQuemada { get; set; }

        [Display(Name = "Quemada Programada")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        [Range(0, Double.MaxValue, ErrorMessage = "El valor debe ser positivo")]
        public decimal cantQuemadaProgram { get; set; }

        [Display(Name = "Caña Verde")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        [Range(0, Double.MaxValue, ErrorMessage = "El valor debe ser positivo")]
        public decimal cantVerde { get; set; }

        public int Usuarioid { get; set; }
        public int Zafrasid { get; set; }
    
        public virtual Campo Campo { get; set; }

        [Display(Name = "Plan de Operador")]
        public virtual PlanOperadoresCombinadas PlanOperadoresCombinadas { get; set; }
        public virtual EstadoEquipo EstadoEquipo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Zafras Zafras { get; set; }
    }
}
