//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiarioEquiposZafra
    {
        [Required(ErrorMessage = "Este Campo es requerido")]
        public int PlanEquiposAgricZafraid { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        public System.DateTime fecha { get; set; }

        [Display(Name = "Arrobas Tiradas")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        [Range(0, Double.MaxValue, ErrorMessage = "El valor debe ser positivo")]
        public decimal arrobasTiradas { get; set; }

        [Display(Name = "Parque Parado")]
        [Remote("CheckParqueParado", "DiarioEquiposZafra", AdditionalFields = "PlanEquiposAgricZafraid", ErrorMessage = "El parque parado no puede ser mayor que el parque asignado")]
        [Range(0, int.MaxValue, ErrorMessage = "El valor debe ser positivo")]
        public int parqueParado { get; set; }
        
        public int Usuarioid { get; set; }

        public int Zafrasid { get; set; }
    
        public virtual Zafras Zafras { get; set; }
        public virtual PlanEquiposAgricZafra PlanEquiposAgricZafra { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
