//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperadorCombinada
    {
        public OperadorCombinada()
        {
            this.PlanOperadoresCombinadas = new HashSet<PlanOperadoresCombinadas>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Operador")]
        [Remote("CheckOperador", "OperadorCombinada", AdditionalFields = "id", ErrorMessage = "Ya existe este Operador")]
        public string nombreOperador { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        public int MarcasCombinadasid { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        public int PelotonCombinadasid { get; set; }
    
        public virtual MarcasCombinadas MarcasCombinadas { get; set; }

        [Display(Name = "Activo")]
        public bool activo { get; set; }

        [Display(Name = "Peloton de Combinadas")]
        public virtual PelotonCombinadas PelotonCombinadas { get; set; }
        public virtual ICollection<PlanOperadoresCombinadas> PlanOperadoresCombinadas { get; set; }
    }
}
