//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanOperadoresCombinadas
    {
        public PlanOperadoresCombinadas()
        {
            this.DiarioOperadorCombinadas = new HashSet<DiarioOperadorCombinadas>();
        }
    
        public int id { get; set; }

        public int OperadorCombinadaid { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Tarea Diaria")]
        [Range(0, Double.MaxValue, ErrorMessage = "El valor debe ser positivo")]
        public decimal tareaDiaria { get; set; }

        public int CentrosRecepcionid { get; set; }

        public int Zafrasid { get; set; }
    
        public virtual CentrosRecepcion CentrosRecepcion { get; set; }
        public virtual ICollection<DiarioOperadorCombinadas> DiarioOperadorCombinadas { get; set; }
        public virtual OperadorCombinada OperadorCombinada { get; set; }
        public virtual Zafras Zafras { get; set; }
    }
}
