//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEquiposAgricZafra
    {
        public PlanEquiposAgricZafra()
        {
            this.DiarioEquiposZafra = new HashSet<DiarioEquiposZafra>();
        }
    
        public int id { get; set; }

        public int ParqueEquiposid { get; set; }

        [Range(0, Double.MaxValue, ErrorMessage = "El valor debe ser positivo")]
        [Remote("CheckParqueAsignado", "PlanEquiposAgricZafra", ErrorMessage = "La cantidad de parque asignado no puede ser mayor que la cantidad de equipos del parque", AdditionalFields = "ParqueEquiposid")]
        public int parqueAsignado { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Tarea Diaria")]
        [Range(0, Double.MaxValue, ErrorMessage = "El valor debe ser positivo")]
        public decimal tareaDiaria { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        public int CentrosRecepcionid { get; set; }

        public int Zafrasid { get; set; }

    
        public virtual CentrosRecepcion CentrosRecepcion { get; set; }
        public virtual ICollection<DiarioEquiposZafra> DiarioEquiposZafra { get; set; }
        public virtual ParqueEquipos ParqueEquipos { get; set; }
        public virtual Zafras Zafras { get; set; }
    }
}
