//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.Usuario = new HashSet<Usuario>();
        }

        public int id { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Rol")]
        public string descripcionRol { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
