//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposSectorPropiedad
    {
        public TiposSectorPropiedad()
        {
            this.Suministradores = new HashSet<Suministradores>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Tipo Sector")]
        [Remote("CheckTipoSector", "TiposSectorPropiedad", AdditionalFields = "id", ErrorMessage = "Ya existe este Sector de Propiedad")]
        public string nombreTipoSector { get; set; }
    
        public virtual ICollection<Suministradores> Suministradores { get; set; }
    }
}
