//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.DiarioEquiposZafra = new HashSet<DiarioEquiposZafra>();
            this.DiarioOperadorCombinadas = new HashSet<DiarioOperadorCombinadas>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Nombre Usuario")]
        [Remote("CheckUser", "Usuario", AdditionalFields = "id", ErrorMessage = "Ya existe un usuario con ese nombre", HttpMethod = "POST")]
        public string nombreUsuario { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        [StringLength(Int32.MaxValue,MinimumLength = 5,ErrorMessage = "La contraseña debe tener mas de 5 caracteres")]
        public string pass { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        public int Rolid { get; set; }

        [Display(Name = "Activo")]
        public bool activo { get; set; }

        public virtual ICollection<DiarioEquiposZafra> DiarioEquiposZafra { get; set; }
        public virtual ICollection<DiarioOperadorCombinadas> DiarioOperadorCombinadas { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
