//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariedadCana
    {
        public VariedadCana()
        {
            this.Campo = new HashSet<Campo>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Variedad de Caña")]
        [Remote("CheckVariedad", "VariedadCana", AdditionalFields = "id", ErrorMessage = "Ya existe esta variedad")]
        public string nombreVariedad { get; set; }
    
        public virtual ICollection<Campo> Campo { get; set; }
    }
}
