//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionZafra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Campo> Campo { get; set; }
        public DbSet<CentrosRecepcion> CentrosRecepcion { get; set; }
        public DbSet<DiarioEquiposZafra> DiarioEquiposZafra { get; set; }
        public DbSet<DiarioOperadorCombinadas> DiarioOperadorCombinadas { get; set; }
        public DbSet<EstadoEquipo> EstadoEquipo { get; set; }
        public DbSet<MarcasCombinadas> MarcasCombinadas { get; set; }
        public DbSet<OperadorCombinada> OperadorCombinada { get; set; }
        public DbSet<ParametrosGenerales> ParametrosGenerales { get; set; }
        public DbSet<ParqueEquipos> ParqueEquipos { get; set; }
        public DbSet<PelotonCombinadas> PelotonCombinadas { get; set; }
        public DbSet<PlanEquiposAgricZafra> PlanEquiposAgricZafra { get; set; }
        public DbSet<PlanOperadoresCombinadas> PlanOperadoresCombinadas { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Suministradores> Suministradores { get; set; }
        public DbSet<TipoEquipos> TipoEquipos { get; set; }
        public DbSet<TiposSectorPropiedad> TiposSectorPropiedad { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<VariedadCana> VariedadCana { get; set; }
        public DbSet<Zafras> Zafras { get; set; }
    }
}
