//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using GestionZafra.Filters;

namespace GestionZafra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zafras
    {
        public Zafras()
        {
            this.DiarioEquiposZafra = new HashSet<DiarioEquiposZafra>();
            this.DiarioOperadorCombinadas = new HashSet<DiarioOperadorCombinadas>();
            this.ParametrosGenerales = new HashSet<ParametrosGenerales>();
            this.PlanEquiposAgricZafra = new HashSet<PlanEquiposAgricZafra>();
            this.PlanOperadoresCombinadas = new HashSet<PlanOperadoresCombinadas>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Zafra")]
        [Remote("CheckZafra","Zafras",AdditionalFields = "id",ErrorMessage = "Ya existe esta zafra")]
        [RegularExpression(@"\d{4}-\d{4}", ErrorMessage = "Debe seguir este patron [año]-[año](Ej: 2014-2015) ")]
        public string descripcionZafra { get; set; }

        [Required(ErrorMessage = "Este Campo es requerido")]
        [Display(Name = "Fecha Inicio")]
        [DataType(DataType.Date)]
        [Remote("CheckFechaInicio","Cierre",AdditionalFields = "id",ErrorMessage = "Esta fecha se encuentra dentro del periodo de otra zafra")]
        public System.DateTime fechaInicio { get; set; }

        [Display(Name = "Fecha Fin")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechaFin { get; set; }
    
        public virtual ICollection<DiarioEquiposZafra> DiarioEquiposZafra { get; set; }
        public virtual ICollection<DiarioOperadorCombinadas> DiarioOperadorCombinadas { get; set; }
        public virtual ICollection<ParametrosGenerales> ParametrosGenerales { get; set; }
        public virtual ICollection<PlanEquiposAgricZafra> PlanEquiposAgricZafra { get; set; }
        public virtual ICollection<PlanOperadoresCombinadas> PlanOperadoresCombinadas { get; set; }
    }
}
